### ISSUE TITLE
Doesn't work at all.

### ISSUE THREAD

**Issue by ed6767** [PolyEdge/project-downloader#1]
Assets take ages to download.
Redundent.

**Comment by PolyEdge** [comment]
@edxtech thank you for your very insightful and helpful report. 
I'll get to fixing up this abandoned project which I replaced and depreciated over 6 months ago.

Even though in my testing environment, the largest projects took less than 10 seconds--quality hardware =)

**Comment by PolyEdge** [comment]
Jokes aside, I replaced this poorly coded project a long time ago, and the replacement is much faster and more efficient, but it's in no state to be pushed to this repository. 

If you're looking for a better python implementation, I don't have it with me right at this moment because I'm vacationing so I can't upload it until I get back

**Comment by edxtech** [comment]
Meh. I just made my own JavaScript one
http://edxtech.github.io/scratchdownload/
But thanks for replying tho

**Comment by ed6767** [comment]
That was pure cringe, 12-year-old me totally knew how to make insightful issues lol

**Comment by PolyEdge** [comment]
dw, you should have seen the things I said when I was that age lol
